repos:
- repo: https://github.com/PyCQA/bandit
  rev: 1.9.2
  hooks:
  - id: bandit
    exclude: tests/
    skips: ["B608",]

- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    exclude: migrations/

- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    args: ["--preview","--config","pyproject.toml"]

- repo: https://github.com/PyCQA/isort
  rev: 7.0.0
  hooks:
  - id: isort
    exclude: build-run-commands/
    args: ["--profile=black", --line-length=79]