"""Add user role, upload quota tracking, and file size

Revision ID: 4262ff5f798e
Revises: 5db91fec1efd
Create Date: 2025-12-30 17:00:35.586183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4262ff5f798e'
down_revision: Union[str, None] = '5db91fec1efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the UserRole enum type first
    user_role_enum = sa.Enum('STANDARD', 'ADMIN', 'PREMIUM', name='userrole')
    user_role_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('files', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('role', user_role_enum, nullable=False, server_default='STANDARD'))
    op.add_column('users', sa.Column('upload_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('upload_quota_reset_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'upload_quota_reset_date')
    op.drop_column('users', 'upload_count')
    op.drop_column('users', 'role')
    op.drop_column('files', 'file_size')
    
    # Drop the enum type
    user_role_enum = sa.Enum('STANDARD', 'ADMIN', 'PREMIUM', name='userrole')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
