"""add original_filename and mime_type to files

Revision ID: 5db91fec1efd
Revises: e1304f2542e0
Create Date: 2025-12-28 21:28:00.635545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db91fec1efd'
down_revision: Union[str, None] = 'e1304f2542e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('files', sa.Column('mime_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'mime_type')
    op.drop_column('files', 'original_filename')
    # ### end Alembic commands ###
