"""add api_key_salt to users

Revision ID: e1304f2542e0
Revises: 5844d4add1e2
Create Date: 2025-12-28 20:47:03.827996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1304f2542e0'
down_revision: Union[str, None] = '5844d4add1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key_salt', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key_salt')
    # ### end Alembic commands ###
